# Addon Manifest
name: "Smokeping"
version: "1.0.0"
slug: "smokeping"
description: "Network latency monitoring with Smokeping"
url: "https://github.com/jandahl/jdahl-homeassistant-addons"
arch:
  - aarch64
  - amd64
  - armv7
init: false
startup: "services"
boot: "auto"

# Ingress Configuration
ingress: true
ingress_port: 8099
panel_icon: "mdi:chart-bell-curve"
panel_title: "Smokeping"

# Persistent Storage Mapping
map:
  - "addon_config:rw"
  - "data:rw"

# User-configurable options
options:
  owner: "Home Assistant User"
  contact: "user@example.com"
schema:
  owner: "str"
  contact: "email"